<?php
namespace app\mobile\controller;
class Articleclass extends MobileMall {
    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index() {
        $articleclass_model = model('articleclass');
        $condition = array();
        $article_class = $articleclass_model->getArticleclassList($condition);
        ds_json_encode(10000, '',array('article_class' => $article_class));
    }
}