<?php
namespace app\mobile\controller;
class Logout extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 注销
     */
    public function index(){
        if(empty(input('post.username')) || !in_array(input('post.client'), $this->client_type_array)) {
            ds_json_encode(10001,'参数错误1');
        }

        $mbusertoken_model = model('mbusertoken');

        if($this->member_info['member_name'] == trim(input('post.username'))) {
            $condition = array();
            $condition['member_id'] = $this->member_info['member_id'];
            $condition['member_clienttype'] = input('post.client');
            $mbusertoken_model->delMbusertoken($condition);
			session(null);//删除session中的member_id下，因为次登录时要整合cookie中的商品到数据库中

            ds_json_encode(10000,'',1);
        } else {
            ds_json_encode(10001,'参数错误2');
        }
    }
}