<?php

namespace app\mobile\controller;


class Memberinvoice extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 发票信息列表
     */
    public function invoice_list()
    {
        $invoice_model = model('invoice');

        $condition = array();
        $condition['member_id'] = $this->member_info['member_id'];

        $invoice_list = $invoice_model->getInvoiceList($condition, 10, 'invoice_id,invoice_title,invoice_content');

        ds_json_encode(10000, '', array('invoice_list' => $invoice_list));
    }

    /**
     * 发票信息删除
     */
    public function invoice_del()
    {
        $invoice_id = intval(input('post.invoice_id'));
        if ($invoice_id <= 0) {
            ds_json_encode(10001,'参数错误');
        }

        $invoice_model = model('invoice');

        $result = $invoice_model->delInvoice(array('invoice_id' => $invoice_id, 'member_id' => $this->member_info['member_id']));
        if ($result) {
            ds_json_encode(10000, '', 1);
        }
        else {
            ds_json_encode(10001,'删除失败');
        }
    }

    /**
     * 发票信息添加
     */
    public function invoice_add()
    {
        $invoice_model = model('invoice');

        $data = array();
        $data['invoice_state'] = 1;
        $data['invoice_title'] = input('post.invoice_title_select') == 'person' ? '个人' : input('post.invoice_title');
        $data['invoice_content'] = input('post.invoice_content');
        $data['invoice_code'] = input('post.invoice_code');
        $data['member_id'] = $this->member_info['member_id'];
        $result = $invoice_model->addInvoice($data);
        if ($result) {
            ds_json_encode(10000, '', array('invoice_id' => $result));
        }
        else {
            ds_json_encode(10001,'添加失败');
        }
    }

    /**
     * 发票内容列表
     */
    public function invoice_content_list()
    {
        $invoice_content_list = array(
            '明细', '酒', '食品', '饮料', '玩具', '日用品', '装修材料', '化妆品', '办公用品', '学生用品', '家居用品', '饰品', '服装', '箱包', '精品', '家电',
            '劳防用品', '耗材', '电脑配件'
        );
        ds_json_encode(10000, '', array('invoice_content_list' => $invoice_content_list));
    }
}