<?php


namespace app\mobile\controller;
use think\Lang;

class Membervoucher extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
		Lang::load(APP_PATH . 'home/lang/'.config('default_lang').'/voucher.lang.php');
    }

    /**
     * 代金卷列表
     */
    public function voucher_list()
    {
        $voucher_model = model('voucher');
        $voucher_state = !empty(input('post.voucher_state')) ? input('post.voucher_state') : '';
        $voucher_list = $voucher_model->getMemberVoucherList($this->member_info['member_id'], $voucher_state, $this->pagesize);
        $result= array_merge(array('voucher_list' => $voucher_list), mobile_page($voucher_model->page_info));
        ds_json_encode(10000, '',$result);
    }

    /*代金券领取*/
    public function voucher_point()
    {
        $vid = intval(input('post.tid'));

        if ($vid <= 0){
            ds_json_encode(10001,'领取失败');
        }

        $voucher_model = model('voucher');
        //验证是否可以兑换代金券
        $data = $voucher_model->getCanChangeTemplateInfo($vid,$this->member_info['member_id']);
        if ($data['state'] == false){
            ds_json_encode(10001,$data['msg']);
        }
        //添加代金券信息
        $data = $voucher_model->exchangeVoucher($data['info'],$this->member_info['member_id'],$this->member_info['member_name']);
        if ($data['state'] == true){
            ds_json_encode(10000, '', 1);
        } else {
            ds_json_encode(10001,'领取失败');
        }
    }


}