<?php

namespace app\mobile\controller;


class Memberevaluate extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 评论
     */
    public function index()
    {
        $order_id = intval(input('param.order_id'));
        $return = model('memberevaluate', 'logic')->validation($order_id, $this->member_info['member_id']);
        if (isset($return['state'])) {
            ds_json_encode(10001,$return['msg']);
        }
        extract($return['data']);
        ds_json_encode(10000, '',array('order_goods' => $order_goods));
    }

    /**
     * 评论保存
     */
    public function save()
    {
        $order_id = intval(input('post.order_id'));
        $return = model('memberevaluate', 'logic')->validation($order_id, $this->member_info['member_id']);
        if (isset($return['state'])) {
            ds_json_encode(10001,$return['msg']);
        }
        //halt($return);
        extract($return['data']);
        $return = model('memberevaluate', 'logic')->saveorderevaluate($_POST, $order_info, $order_goods, $this->member_info['member_id'], $this->member_info['member_name']);

        if (!$return['state']) {
            ds_json_encode(10001,$return['msg']);
        } else {
            ds_json_encode(10000, '', 1);
        }
    }

    /**
     * 追评
     */
    public function again()
    {
        $order_id = intval(input('param.order_id'));
        $return = model('memberevaluate', 'logic')->validationAgain($order_id, $this->member_info['member_id']);
        if (!$return['state']) {
            ds_json_encode(10001,$return['msg']);
        }
        extract($return['data']);
        ds_json_encode(10000, '', array('evaluate_goods' => $evaluate_goods));
    }

    /**
     * 追加评价保存
     */
    public function save_again()
    {
        $order_id = intval(input('post.order_id'));
        $return = model('memberevaluate', 'logic')->validationAgain($order_id, $this->member_info['member_id']);
        if (!$return['state']) {
            ds_json_encode(10001,$return['msg']);
        }
        extract($return['data']);

        $return = model('memberevaluate', 'logic')->saveAgain($_POST, $order_info, $evaluate_goods);
        if (!$return['state']) {
            ds_json_encode(10001,$return['msg']);
        } else {
            ds_json_encode(10000, '', 1);
        }
    }

    /**
     * 虚拟订单评价
     */
    public function vr()
    {
        $order_id = intval(input('param.order_id'));
        $return = model('memberevaluate', 'logic')->validationVr($order_id, $this->member_info['member_id']);
        if (isset($return['state'])) {
            ds_json_encode(10001,$return['msg']);
        }
        extract($return['data']);
        ds_json_encode(10000,'',array('order_info' => $order_info));

    }

    /**
     * 虚拟订单评价保存
     */
    public function save_vr()
    {
        $order_id = intval(input('post.order_id'));
        $return = model('memberevaluate', 'logic')->validationVr($order_id, $this->member_info['member_id']);
        if (isset($return['state'])) {
            ds_json_encode(10001,$return['msg']);
        }
        extract($return['data']);

        $return = model('memberevaluate', 'logic')->saveVr();
        if (!$return['state']) {
            ds_json_encode(10001, $return['msg']);
        } else {
            ds_json_encode(10000, '', 1);
        }
    }
}