<?php
namespace app\mobile\controller;

class Memberaddress extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 地址列表
     */
    public function address_list()
    {
        $address_model = model('address');
        $address_list = $address_model->getAddressList(array('member_id' => $this->member_info['member_id']));
        ds_json_encode(10000, '',array('address_list' => $address_list));
    }

    /**
     * 地址详细信息
     */
    public function address_info()
    {
        $address_id = intval(input('post.address_id'));

        $address_model = model('address');

        $condition = array();
        $condition['address_id'] = $address_id;
        $address_info = $address_model->getAddressInfo($condition);
        if (!empty($address_id) && $address_info['member_id'] == $this->member_info['member_id']) {
            ds_json_encode(10000, '',array('address_info' => $address_info));
        }
        else {
            ds_json_encode(10001,'地址不存在');
        }
    }

    /**
     * 删除地址
     */
    public function address_del()
    {
        $address_id = intval(input('post.address_id'));

        $address_model = model('address');

        $condition = array();
        $condition['address_id'] = $address_id;
        $condition['member_id'] = $this->member_info['member_id'];
        $address_model->delAddress($condition);
        ds_json_encode(10000, '', 1);

    }

    /**
     * 新增地址
     */
    public function address_add()
    {
        $address_model = model('address');

        $address_info = $this->_address_valid();

        $result = $address_model->addAddress($address_info);
        if ($result) {
            ds_json_encode(10000, '',array('address_id' => $result));
        }
        else {
            ds_json_encode(10001,'保存失败');
        }
    }

    /**
     * 编辑地址
     */
    public function address_edit()
    {
        $address_id = intval(input('post.address_id'));

        $address_model = model('address');

        //验证地址是否为本人
        $address_info = $address_model->getOneAddress($address_id);
        if ($address_info['member_id'] != $this->member_info['member_id']) {
            ds_json_encode(10001,'参数错误');
        }

        $address_info = $this->_address_valid();
        $result = $address_model->editAddress($address_info, array('address_id' => $address_id,'member_id'=>$this->member_info['member_id']));
        if ($result) {
            ds_json_encode(10000, '', 1);
        }
        else {
            ds_json_encode(10001,'保存失败');
        }
    }

    /**
     * 验证地址数据
     */
    private function _address_valid()
    {
        $data=[
            'address_realname'=>input('post.true_name'),
            'area_info'=>input('post.area_info'),
            'address_detail'=>input('post.address'),
        ];

        if (empty(input('post.mob_phone'))&&empty(input('post.tel_phone'))){
            $data['address_mob_phone']='';
        }

        $memberaddress_validate = validate('memberaddress');
        if (!$memberaddress_validate->scene('address_valid')->check($data)) {
            ds_json_encode(10001,$memberaddress_validate->getError());
        }

        $data = array();
        $data['member_id'] = $this->member_info['member_id'];
        $data['address_realname'] = input('post.true_name');
        $data['area_id'] = intval(input('post.area_id'));
        $data['city_id'] = intval(input('post.city_id'));
        $data['area_info'] = input('post.area_info');
        $data['address_detail'] = input('post.address');
        $data['address_longitude'] = input('post.longitude');
        $data['address_latitude'] = input('post.latitude');
        $data['address_tel_phone'] = !empty(input('post.tel_phone'))?input('post.tel_phone'):'';
        $data['address_mob_phone'] = !empty(input('post.mob_phone'))?input('post.mob_phone'):'';
        $data['address_is_default'] = input('post.is_default');
        return $data;
    }

    /**
     * 地区列表
     */
    public function area_list()
    {
        $area_id = intval(input('post.area_id'));

        $area_model = model('area');

        $condition = array();
        if ($area_id > 0) {
            $condition['area_parent_id'] = $area_id;
        }
        else {
            $condition['area_deep'] = 1;
        }
        $area_list = $area_model->getAreaList($condition, 'area_id,area_name');
        ds_json_encode(10000, '',array('area_list' => $area_list));
    }
}