<?php

namespace app\mobile\controller;

class Membergoodsbrowse extends MobileMember {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 我的足迹
     */
    public function browse_list() {
        $goodsbrowse_model = model('goodsbrowse');
        //查询浏览记录
        $where = array();
        $where['member_id'] = $this->member_info['member_id'];
        $browselist = $goodsbrowse_model->getViewedGoodsList($this->member_info['member_id'], $this->pagesize);
        $goodsid_arr = array();
        foreach ((array) $browselist as $k => $v) {
            $goodsid_arr[] = $v['goods_id'];
        }
        //查询商品信息
        $browselist_new = array();
        if ($goodsid_arr) {
            $goods_list_tmp = model('goods')->getGoodsList(array(
                'goods_id' => array(
                    'in', $goodsid_arr
                )), 'goods_id, goods_name, goods_promotion_price,goods_promotion_type, goods_marketprice, goods_image, gc_id, gc_id_1, gc_id_2, gc_id_3');
            $goods_list = array();
            foreach ((array) $goods_list_tmp as $v) {
                $goods_list[$v['goods_id']] = $v;
            }
            foreach ($browselist as $k => $v) {
                if ($goods_list[$v['goods_id']]) {
                    $tmp = $goods_list[$v['goods_id']];
                    $tmp["goodsbrowse_time"] = $v['goodsbrowse_time'];
                    $tmp["goods_image_url"] = goods_cthumb($goods_list[$v['goods_id']]['goods_image'], 480);
                    if (date('Y-m-d', $v['goodsbrowse_time']) == date('Y-m-d', time())) {
                        $tmp['browsetime_day'] = '今天';
                    } elseif (date('Y-m-d', $v['goodsbrowse_time']) == date('Y-m-d', (time() - 86400))) {
                        $tmp['browsetime_day'] = '昨天';
                    } else {
                        $tmp['browsetime_day'] = date('Y年m月d日', $v['goodsbrowse_time']);
                    }
                    $tmp['browsetime_text'] = $tmp['browsetime_day'] . date('H:i', $v['goodsbrowse_time']);
                    $browselist_new[] = $tmp;
                }
            }
        }
        $result= array_merge(array('goodsbrowse_list' => $browselist_new), mobile_page($goodsbrowse_model->page_info));
        ds_json_encode(10000, '',$result);
    }

    /**
     * 清空足迹
     */
    public function browse_clearall() {
        if (model('goodsbrowse')->delGoodsbrowse(array('member_id' => $this->member_info['member_id']))) {
            ds_json_encode(10000,'',1);
        } else {
            ds_json_encode(10001,'清空失败');
        }
    }

}